### ISSUE TITLE
Unable to use Nuget package in signed application

### ISSUE THREAD

**Issue by camalot** [dwmkerr/consolecontrol#15]
Referenced assembly 'ConsoleControl' does not have a string name.

My application is signed, I cannot use the nuget package of ConsoleControl because it is not signed.

**Comment by dwmkerr** [comment]
Thanks for raising this issue, the assembly should be signed indeed, I'll sort that now.

**Comment by dwmkerr** [comment]
Fixed in 1.1, will be released shortly.
