### ISSUE TITLE
No license is specified for this project

### ISSUE THREAD

**Issue by david-mitchell** [dwmkerr/consolecontrol#16]
I'm interested in using code from this project, but it is unclear what the terms are for doing so.

**Comment by david-mitchell** [comment]
I just found a link to the license on the Code Project page. It would be cool if this repo also included a License file.

**Comment by dwmkerr** [comment]
Hi @david-mitchell thanks for getting in touch, I've added the highly permissive MIT license and updated the CP article.

**Comment by david-mitchell** [comment]
:+1: Thanks!
