### ISSUE TITLE
Multiple Console Windows

### ISSUE THREAD

**Issue by markentingh** [dwmkerr/consolecontrol#23]
I am writing an app using your control (thank you so much for such an amazing control btw), but I cannot seem to use more than one instance of the control on a single form. When I execute the function StartProcess("cmd",null) on each instance, only one instance loads command prompt.

**Comment by markentingh** [comment]
I just realized, it was an issue with creating new tabs in the tab control, creating a new console for the new tab, but not giving the tab focus. Once I gave the tab focus (before executing StartProcess), the console works correctly.

**Comment by jtorjo** [comment]
Hey, 

Funny - I'm doing the same thing - see my fork as well if you want.
