### ISSUE TITLE
"Could not load file or assembly 'ConsoleControlAPI, Version=1.2.0.0" in WinForms App. 

### ISSUE THREAD

**Issue by stianlarsen** [dwmkerr/consolecontrol#35]
I get this error message, both trying to add to form using the designer and while creating and adding the control using code. 

"Could not load file or assembly 'ConsoleControlAPI, Version=1.2.0.0, Culture=neutral, PublicKeyToken=7c86b8a36b9c33e2' or one of its dependencies. The system cannot find the file specified."

ConsoleControl.dll and .xml sits right beside the .exe in the /bin/debug folder. 

Loading it dynamically and doing a assembly.GetTypes() works. Doing Activator.CreateInstance on the type fails with the same exception however.

**Comment by jobrittain** [comment]
I've got the same problem with a WPF application.

**Comment by dwmkerr** [comment]
Hmm strange, did you install with Nuget?

**Comment by vkonar-ARNA** [comment]
I'm having the same issue as well. I have the nuget downloaded but its still gives the same error.

**Comment by jobrittain** [comment]
> Hmm strange, did you install with Nuget?

Yes, I installed the NuGet package in a project targeting .NET 4.7.1.

**Comment by aboodh95** [comment]
any update about this issue, I just installed it using NuGet and I'm getting this error in case I add it in run time 
![image](https://user-images.githubusercontent.com/12459798/55058618-e38c3580-5085-11e9-9631-7e98c919ffaa.png)

and in case I drag it from the toolbox I will  get
![image](https://user-images.githubusercontent.com/12459798/55058652-01f23100-5086-11e9-87dc-1587f52ce129.png)

**Comment by aboodh95** [comment]
i downgrade it from 1.2 to 1.1 and it's working

**Comment by iainross** [comment]
Likewise, I installed 1.2 from nuget and the control couldn't be created because it couldn't find ConsoleControlAPI.  Neither 1.1.0 nor the separate package for 1.0.3 show the problem.

**Comment by jorisvergeer** [comment]
It's just that the ConsoleControlAPI is no packed in the 1.2.0 ConsoleControl nuget package.

**Comment by dwmkerr** [comment]
Got it - fixing now. Thanks for the heads up friends!

**Comment by dwmkerr** [comment]
Should be fixed with release 1.2.1, but let me know if you come across any other issues!
