### ISSUE TITLE
Can't Launch Node

### ISSUE THREAD

**Issue by YamanAlhalabi** [dwmkerr/consolecontrol#41]
I am working on a web IDE that has node functionality, sadly can't open node

**Comment by dwmkerr** [comment]
Sorry can you leave more details? The exact issue you are seeing, how to reproduce, error messages, stack traces, anything which might help!

**Comment by YamanAlhalabi** [comment]
Hello, I am sorry that I didn't provide that much info, it's my fault, I was on a hurry
Anyways I am using the control to launch node.js, I tried using `consoleControl.StartProcess("node")` It just returned nothing, I tried to make a batch file to start it same problem, tried opening cmd then inserting node command. Sadly nothing worked. And I very thankful that you are willing to help me, I really appreciate that, Thank You. But I made a Console App to call node.js and it worked so that's fine if my code can help you this is it :
`             ProcessStartInfo myProcessStartInfo = new ProcessStartInfo(args[0], args[1]);
                myProcessStartInfo.UseShellExecute = false;
                myProcessStartInfo.RedirectStandardOutput = true;
                myProcess.StartInfo = myProcessStartInfo;
                myProcess.Start();
                StreamReader myStreamReader = myProcess.StandardOutput;
                // Read the standard output of the spawned process.
                while (myStreamReader.EndOfStream == false)
                {
                    string myString = myStreamReader.ReadLine();
                    Console.WriteLine(myString);
                }

                myProcess.WaitForExit();
                myProcess.Close();
                
`

**Comment by YamanAlhalabi** [comment]
I am very thankful for you anyways.

**Comment by dwmkerr** [comment]
Hi @YamanAlhalabi did you manage to solve the issue? I can take a look into this, might be a few days tho!

**Comment by YamanAlhalabi** [comment]
Yes, I did, I am having a problem which involves clearing the screen by using the 
```Console.Clear()

```
Excuting that would just crash the hosted app, can you please give me a way to clean it safely

**Comment by dwmkerr** [comment]
Excellent - what did you do to fix the Node issue? Do you have the stack trace of the error you are seeing for the `Clear` issue?

**Comment by dwmkerr** [comment]
I wonder if it is related to this #40

**Comment by YamanAlhalabi** [comment]
I provided the code above 😁

**Comment by dwmkerr** [comment]
Sorry, my bad! Will check into the clear issue shortly!
