### ISSUE TITLE
WPF line spacing is too large

### ISSUE THREAD

**Issue by ChaosinaCan** [dwmkerr/consolecontrol#7]
The rich text box in ConsoleControl.xaml uses double line spacing, so it does not look like a proper console. Adding the following to the `<RichTextBox>` element fixes it to single line spacing.

```C#
<RichTextBox.Resources>
	<Style TargetType="{x:Type Paragraph}">
		<Setter Property="Margin" Value="0" />
	</Style>
</RichTextBox.Resources>
```

**Comment by dwmkerr** [comment]
Fixed in 1.1, release will be made shortly.
